config/routes.rb
Rails.application.routes.draw do
  resources :sessions, :only => [:new, :create, :destroy]

  resources :microposts

  resources :users

  resources :videos

  get 'pages/about'

  get 'pages/contact'

  get 'pages/greeting'

  root 'pages#greeting'

  match '/signup' => 'users#new', via: [:get]
  match '/signin' => 'sessions#new', via: [:get]
  match '/signout' => 'sessions#destroy', via: [:delete]

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :microposts
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, :presence => true, :length => {:maximum => 30}
	validates :email, :presence => true, :format => {:with => email_regex}, :uniqueness => true
	validates :password, :presence => true, :confirmation => true, :length => {:within => 6..40}

	before_save :encrypt_password

	def has_password?(submitted_password)
		encrypted_password == encrypt(submitted_password)
	end

	def self.authenticate(email, submitted_password)
		user = find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
	end

	def self.authenticate_with_salt(id, cookie_salt)
		user = find_by_id(id)
		(user && user.salt == cookie_salt) ? user : nil
	end

	private
		def encrypt_password
			self.salt = make_salt if new_record?
			self.encrypted_password = encrypt(password)
			self.password = nil
		end
		def encrypt(string)
			secure_hash("#{salt}--#{string}")
		end
		def make_salt
			secure_hash("#{Time.now.utc}--#{password}")
		end
		def secure_hash(string)
			Digest::SHA2.hexdigest(string)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, :only => [:index, :edit, :update]
  before_action :correct_user, :only => [:edit, :update]
  before_action :admin_user, :only => :destroy

  # GET /users
  # GET /users.json
  def index
    #@users = User.all
    @users = User.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @title = "Sign up"
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @title = "Edit user"
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to @user, success: 'Welcome to the Sample App!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def authenticate
      deny_access unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless correct_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, className = "gravatar", options = {:size => 50})
		gravatar_image_tag(user.email.downcase, :alt => user.name, :class => className, :gravatar => options)
	end
end

app/views/users/_form.html.erb
<div class="row">
  <%= form_for(@user, :html => {:class => "col m6 s12"}) do |f| %>

    <%= render 'shared/error_messages' %>

    <div class="input-field">
      <i class="mdi-action-account-circle prefix"></i>
      <%= f.text_field :name, :length => '30', :placeholder => 'Name' %>
    </div>
    <div class="input-field">
      <i class="mdi-action-lock prefix"></i>
      <%= f.password_field :password, :placeholder => 'Password' %>
    </div>
    <div class="input-field">
      <i class="mdi-action-lock prefix"></i>
      <%= f.password_field :password_confirmation, :placeholder => 'Password Confirmation' %>
    </div>
    <div class="input-field">
      <i class="mdi-communication-email prefix"></i>
      <%= f.text_field :email, :length => '40', :placeholder => 'Email' %>
    </div>
    <div class="actions">
      <button class="btn waves-effect waves-light" type="submit" name="commit">Create User
        <i class="mdi-content-send right"></i>
      </button>
    </div>
  <% end %><!--end form-->
  <div class="col m6 s12">
    <%= image_tag "JoinUs.jpg", :class => "responsive-img" %>
  </div>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<div class="row">
  <%= form_for(@user, :html => {:class => "col m6 s12"}) do |f| %>

    <%= render 'shared/error_messages' %>

    <div class="input-field">
      <i class="mdi-action-account-circle prefix"></i>
      <%= f.text_field :name, :length => '10', :placeholder => 'Name' %>
    </div>
    <div class="input-field">
      <i class="mdi-action-lock prefix"></i>
      <%= f.password_field :password, :placeholder => 'Password' %>
    </div>
    <div class="input-field">
      <i class="mdi-action-lock prefix"></i>
      <%= f.password_field :password_confirmation, :placeholder => 'Password Confirmation' %>
    </div>
    <div class="input-field">
      <i class="mdi-communication-email prefix"></i>
      <%= f.text_field :email, :length => '40', :placeholder => 'Email' %>
    </div>
    <div class="actions">
      <button class="btn waves-effect waves-light" type="submit" name="commit">Update
        <i class="mdi-content-send right"></i>
      </button>
    </div>
  <% end %><!--end form-->
  <div class="col m6 s12">
    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>

</div>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<%= will_paginate %>

<ul class="collection">
    <% @users.each do |user| %>
    <li class="collection-item avatar">
        <%= gravatar_for user, "circle", :size => 30 %>
        <span class="title"><%= user.name %><br><%= user.email %></span>
        <span class="right">
            <%= link_to 'Show', user %>
            <% if current_user.admin? %>
            <%= link_to 'Edit', edit_user_path(user) %>
            <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
        </span>
    </li>
    <% end %>
</ul>

<%= will_paginate %>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<div><%= gravatar_for @user %></div>

<p>
	URL: <%= link_to user_path(@user), @user %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>