config/routes.rb
Rails.application.routes.draw do
  resources :sessions, :only => [:new, :create, :destroy]

  resources :microposts

  resources :users

  resources :videos

  get 'pages/about'

  get 'pages/contact'

  get 'pages/greeting'

  root 'pages#greeting'

  match '/signup' => 'users#new', via: [:get]
  match '/signin' => 'sessions#new', via: [:get]
  match '/signout' => 'sessions#destroy', via: [:delete]

end

app/models/video.rb
class Video < ActiveRecord::Base
	validates :wistia, :length => { :maximum => 10 }
	def next
		Video.where("id > ?", id).first
	end
	def prev
		Video.where("id < ?", id).last
	end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @videos = Video.all

    @next_video = @video.next
    @prev_video = @video.prev
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:wistia, :description, :title)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= f.text_field :wistia, :placeholder => 'Link', :length => '10' %>
  </div>
  <div class="input-field">
    <%= f.text_field :title, :placeholder => 'Title', :length => '20' %>
  </div>
  <div class="input-field">
    <%= f.text_area :description, :placeholder => 'Description', :length => '800', :class => 'materialize-textarea' %>
  </div>
  <button class="btn waves-effect waves-light" type="submit" name="action">Submit</button>
  <a href="<%= videos_path %>" class="btn waves-effect waves-light" name="action">Back</a>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<div class="card">
	<div class="card-content">
		<%= render 'form' %>
	</div>
</div>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Videos</h1>

<%= link_to new_video_path, :class => 'btn-floating btn-large waves-effect waves-light red' do %>
  <i class="mdi-content-add"></i>
<% end %>

<ul class="collapsible" data-collapsible="accordion">
  <% @videos.each do |video| %>
    <li>
      <div class="collapsible-header">
        <i class="mdi-av-my-library-books"></i>
        <%= link_to video.title, video %>
        <span class="right">
          <%= link_to edit_video_path(video) do %>
            <i class="mdi-content-create"></i><% end %>
          <%= link_to video, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="mdi-notification-event-busy"></i><% end %>
        </span>
      </div>
      <div class="collapsible-body"><p><%= video.description %></p></div>
    </li>
  <% end %>
</ul>

app/views/videos/new.html.erb
<h1>New video</h1>

<div class="card">
	<div class="card-content">
		<%= render 'form' %>
	</div>
</div>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col m3">
		<div class="collection">
			<% @videos.each do |video| %>
				<%= link_to video.title, video, :class => 'collection-item' %>
			<% end %>
		</div>
	</div>
	<div class="col m9">
		<div class="card blue-grey darken-1">
			<div class="card-image">
				<div id="wistia_<%= @video.wistia %>"></div>
			</div>
			
			<div class="card-content white-text">
				<button class="btn btn-primary" onclick="setPlaySpeed(0.75)">0.75x</button>
				<button class="btn btn-primary" onclick="setPlaySpeed(1)">1x</button>
				<button class="btn btn-primary" onclick="setPlaySpeed(2)">2x</button>
				<br>
				<span class="card-title"><%= @video.title %></span>
				<p><%= @video.description %></p>
			</div>
			<div class="card-action">
				<%= link_to "Previous", @prev_video if !@prev_video.nil? %>
				<span class="right">
					<%= link_to "Next", @next_video if !@next_video.nil? %>
				</span>
			</div>
		</div>
	</div>
</div>

<script src="http://fast.wistia.net/static/E-v1.js"></script>
<script>
wistiaEmbed = Wistia.embed("<%= @video.wistia %>", {
  videoQuanlity: "hd-only",
  videoFoam: true // responsive
});
function setPlaySpeed(speed) {
	wistiaEmbed.playbackRate(speed);
}
</script>