config/routes.rb
Rails.application.routes.draw do
  resources :sessions, :only => [:new, :create, :destroy]

  resources :microposts

  resources :users

  resources :videos

  get 'pages/about'

  get 'pages/contact'

  get 'pages/greeting'

  root 'pages#greeting'

  match '/signup' => 'users#new', via: [:get]
  match '/signin' => 'sessions#new', via: [:get]
  match '/signout' => 'sessions#destroy', via: [:delete]

end

app/views/layouts/_navigation.html.erb
<nav>
    <div class="nav-wrapper teal lighten-2">
        <%= link_to "Music4Life", root_path, :class => "brand-logo" %>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
        <ul class="right hide-on-med-and-down">
            <li><%= link_to "Sign up now", signup_path, :class => "waves-effect blue btn-large white-text" %></li>
            <li><a href="<%= pages_about_path %>" title="About"><i class="mdi-action-track-changes"></i></a></li>
            <li><a href="<%= pages_contact_path %>" title="Contact"><i class="mdi-action-perm-phone-msg"></i></a></li>
            <% if signed_in? %>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
            <% else %>
                <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
        </ul>
        <ul class="side-nav" id="mobile-demo">
            <li><%= link_to "Sign up now", signup_path %></li>
            <li><a href="<%= pages_about_path %>" title="About">About</a></li>
            <li><a href="<%= pages_contact_path %>" title="Contact">Contact</a></li>
        </ul>
    </div>
</nav>

app/views/layouts/_stylesheets.html.erb
<!-- Compiled and minified CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/css/materialize.min.css">

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<!--Let browser know website is optimized for mobile-->
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>


<!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/js/materialize.min.js"></script>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= title %></title>
        <%= render 'layouts/stylesheets' %>
    </head>
    <body>
        <%= render 'layouts/navigation' %>


        <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>

        <div class="row">
            <div class="col m10 offset-m1">
                <%= yield %>
            </div>
        </div>


        <%= debug(params) if Rails.env.development? %>
        <!-- Compiled and minified JavaScript -->
        
        <script>
        $(".button-collapse").sideNav();
        </script>
    </body>
</html>

app/views/layouts/greeting.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= title %></title>
        <%= render 'layouts/stylesheets' %>
    </head>
    <body>

        <%= yield %>

    </body>
</html>